Models available on the Hugging Face hub can serve as a good starting point, but they may not have been trained specifically for the task we are focused on, nor have they necessarily encountered data similar to ours. While these models possess general language knowledge, they may lack the specific task knowledge required for our purposes. Therefore, fine-tuning these models on our own data is an effective way to adapt them to our needs.

<br>
<a target="_blank" href="https://colab.research.google.com/drive/1QogIeR13OmhBs9fif_cycNACscxb5Bt9#scrollTo=EjyJfZJhQ1Uc">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
!pip install -q  scikit-learn datasets tokenizers sentencepiece protobuf accelerate transformers torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 19.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 67.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 101.4 MB/s eta 0:00:00

In [47]:
# set random seed for reproducibility
import numpy as np

SEED_GLOBAL = 42
np.random.seed(SEED_GLOBAL)

In [56]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/luissattelmayer/intro-css/refs/heads/main/data/tweets_annotations.csv")

df = df[["id", "text", "label"]]

df

        id                                               text  label
0     8094  Thank you to the US Army Corps of Engineers fo...      0
1     8050  Biden attacked fossil fuels, paused federal oi...      1
2    32375  Speaker Pelosi said people “will do what they ...      0
3     6004  "As I’ve told Xi Jinping, it is never a good b...      1
4    16668  @CoronadoForXRP @chrislarsensf Great hearing t...      0
..     ...                                                ...    ...
720  58134  This bill would restore privacy for American g...      0
721  29306  Congrats to Luke Dallmann of Oronoco, MN for b...      0
722  59623  Congress and the Nation look forward to Judge ...      0
723  36111  The ongoing journey to form a more perfect Uni...      0
724  41377  Incredible turnout for an incredible exhibit a...      0

[725 rows x 3 columns]

In [58]:
# Create label_text column 1 being about economy and 0 for not

df["label_text"] = df["label"].apply(lambda x: "economy" if x == 1 else "other")

df.value_counts("label_text")

# Remove Missing values

df = df.dropna()

## Split into training and test set

As in classical supervised learning, to fine-tune a pre-trained model, we need to split our dataset into training and testing sets, which can be done using the sklearn library in Python.

In [59]:
# Split into training and test set

from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, test_size=0.2, random_state=SEED_GLOBAL, stratify=df['label'])

# label distribution train set
print("Train set label distribution:\n", df_train.label_text.value_counts(), "\n")
# label distribution test set
print("Test set label distribution:\n", df_test.label_text.value_counts())

Train set label distribution:
 label_text
other      438
economy    142
Name: count, dtype: int64

Test set label distribution:
 label_text
other      109
economy     36
Name: count, dtype: int64

## Load a model

The next step is to load a pre-trained model from the Hugging Face library, which we will fine-tune for our classification task using our labeled dataset. For this, we do not use the pipeline but instead load the model and its associated tokenizer. Here, I load a version of BERT called DeBERTa, but it could be any model that is relevant on the platform.

In [60]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig
import torch
import numpy as np

## load a model and its tokenizer
model_name = "microsoft/deberta-v3-base"
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True, model_max_length=512)

# Define the desired label mapping directly
label2id = {
    'Other': 0,                   # Set 'Other' to 0
    'Economy': 1   # Set 'Economy' to 1
}

# Create an inverse mapping
id2label = {v: k for k, v in label2id.items()}  # Inverse mapping

# Print the mappings to verify
print("Label to ID mapping:", label2id)  # This should print: {'Other': 0, 'Environment and Energy': 1}
print("ID to Label mapping:", id2label)  # This should print: {0: 'Other', 1: 'Environment and Energy'}

config = AutoConfig.from_pretrained(model_name, label2id=label2id, id2label=id2label, num_labels=len(label2id));
print("\n", label2id, "\n")

# load model with config
model = AutoModelForSequenceClassification.from_pretrained(model_name, config=config, ignore_mismatched_sizes=True);

# use GPU (cuda) if available, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
model.to(device)

/usr/local/lib/python3.11/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Label to ID mapping: {'Other': 0, 'Economy': 1}
ID to Label mapping: {0: 'Other', 1: 'Economy'}

 {'Other': 0, 'Economy': 1}

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Device: cuda

DebertaV2ForSequenceClassification(
  (deberta): DebertaV2Model(
    (embeddings): DebertaV2Embeddings(
      (word_embeddings): Embedding(128100, 768, padding_idx=0)
      (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): DebertaV2Encoder(
      (layer): ModuleList(
        (0-11): 12 x DebertaV2Layer(
          (attention): DebertaV2Attention(
            (self): DisentangledSelfAttention(
              (query_proj): Linear(in_features=768, out_features=768, bias=True)
              (key_proj): Linear(in_features=768, out_features=768, bias=True)
              (value_proj): Linear(in_features=768, out_features=768, bias=True)
              (pos_dropout): Dropout(p=0.1, inplace=False)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): DebertaV2SelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): DebertaV2Intermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): DebertaV2Output(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (rel_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
    )
  )
  (pooler): ContextPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0, inplace=False)
  )
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

## Tokenize the data

Transformer models take text data that is already tokenized in a specific manner, which is what we do below for both our training and test sets. BERT has a limit of 512 tokens that it can process, and any text longer than this will be truncated. Since we are working with tweets, this does not pose any problem

In [61]:
# convert pandas dataframes to Hugging Face dataset object to facilitate pre-processing

import datasets

dataset = datasets.DatasetDict({
    "train": datasets.Dataset.from_pandas(df_train),
    "test": datasets.Dataset.from_pandas(df_test)
})


# tokenize
def tokenize(examples):
  return tokenizer(examples["text"], truncation=True, max_length=512)

dataset = dataset.map(tokenize, batched=True)

Map:   0%|          | 0/580 [00:00<?, ? examples/s]

Map:   0%|          | 0/145 [00:00<?, ? examples/s]

## Training the model

Before training the model, we need to specify several key training arguments using the TrainingArguments() function. This function does not actually train the model; instead, it sets the configuration for how the training process will be conducted. These arguments control various aspects of training, such as the number of epochs, batch sizes, learning rate, and evaluation strategies. Once the training arguments are defined, they are used later in the Trainer function to train the model.

- Epochs : Number of times the model will iterate over the entire dataset. More epochs generally improve performance but increase training time.

- Learning rate : Step size used in optimization. A small learning rate can stabilize training, while a larger one may speed up convergence.

- per_device_train_batch_size: Batch size for training. A larger batch size speeds up training but requires more memory. Reduce it if you encounter memory issues.

- per_device_eval_batch_size: Batch size for evaluation, similar to the training batch size. Reducing it helps avoid memory problems during evaluation.

In [62]:
import transformers
from transformers import TrainingArguments, Trainer, logging

training_directory = "BERT-demo"

# Overview of all training arguments: https://huggingface.co/transformers/main_classes/trainer.html#transformers.TrainingArguments
# Hugging Face tipps to increase training speed and decrease out-of-memory (OOM) issues: https://huggingface.co/transformers/performance.html?
from transformers import TrainingArguments

train_args = TrainingArguments(
    output_dir=f"./results/{training_directory}",
    logging_dir=f"./logs/{training_directory}",
    seed=SEED_GLOBAL,
    num_train_epochs=4,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_ratio=0.06,
    weight_decay=0.1,
    gradient_checkpointing=True,
    eval_strategy="steps",
    eval_steps=500,
    logging_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=3,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    report_to="none",
)

Before training a model, it’s crucial to define how the model’s performance will be evaluated during the training process. This typically involves specifying which evaluation metrics will be used to monitor the model's progress. Evaluation metrics are important because they provide feedback on how well the model is learning, guiding decisions such as when to stop training or adjust hyperparameters.

In [63]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
import warnings
import numpy as np

def compute_metrics_standard(eval_pred):
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore")

        labels = eval_pred.label_ids
        pred_logits = eval_pred.predictions
        preds_max = np.argmax(pred_logits, axis=1)  # argmax on each row (axis=1) in the tensor

        # Calculate metrics
        precision, recall, f1, _ = precision_recall_fscore_support(labels, preds_max, average='weighted')  # Weighted for multi-class problems
        accuracy = accuracy_score(labels, preds_max)

        # Return desired metrics
        metrics = {
            'accuracy': accuracy,
            'f1': f1,
            'precision': precision,
            'recall': recall,
        }

        return metrics

Now we can train the model by specifying the Trainer function, which encapsulates all the components necessary for training. This includes the model (which we load from Hugging Face), its tokenizer, the training arguments we defined earlier, the training and test datasets, and the evaluation metrics. Once everything is set up, we launch the training process by calling trainer.train().

In [64]:
# training
trainer = Trainer(
    model=model,
    tokenizer=tokenizer,
    args=train_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    compute_metrics=compute_metrics_standard
)

trainer.train()

/tmp/ipython-input-64-1046365052.py:2: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=292, training_loss=0.41691343751672194, metrics={'train_runtime': 140.9252, 'train_samples_per_second': 16.463, 'train_steps_per_second': 2.072, 'total_flos': 96179093339376.0, 'train_loss': 0.41691343751672194, 'epoch': 4.0})

The model is then evaluated on the test set with trainer.evaluate()

In [65]:
results = trainer.evaluate()
results

{'eval_loss': 0.3305703103542328,
 'eval_accuracy': 0.8620689655172413,
 'eval_f1': 0.867163744581743,
 'eval_precision': 0.8810746142080474,
 'eval_recall': 0.8620689655172413,
 'eval_runtime': 1.1141,
 'eval_samples_per_second': 130.146,
 'eval_steps_per_second': 17.054,
 'epoch': 4.0}

## Inference

In [71]:
from transformers import pipeline

economy_classifier = pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer,
    framework="pt",
    device=device,
)

Device set to use cuda

In [72]:
# Import tweet data

full_corpus = pd.read_csv("https://www.dropbox.com/s/dpu5m3xqz4u4nv7/tweets_house_rep_party.csv?dl=1")
full_corpus

,twitter_handle,date,text,is_retweet,is_quote,party
0,RepAdams,2022-05-07,I'm honored to be @HustonTillotson's 2022 Comm...,False,False,D
1,RepAdams,2022-05-07,https://t.co/9v2NRILpiZ,True,False,D
2,RepAdams,2022-05-06,Honored to join the HT community this weekend!...,False,True,D
3,RepAdams,2022-05-06,"Campus Community and Supporters, Congresswoman...",True,False,D
4,RepAdams,2022-05-06,"Please see below and be safe, Mecklenburg! htt...",False,True,D
...,...,...,...,...,...,...
76109,RepLeeZeldin,2022-03-02,The public isn’t looking to be spun on how wha...,False,False,R
76110,RepLeeZeldin,2022-03-02,Legislating from the presidency wasn’t what ou...,False,False,R
76111,RepLeeZeldin,2022-03-01,Tonight’s State of the Union Address would be ...,False,False,R
76112,RepLeeZeldin,2022-03-01,I’m absolutely certain nobody asked for 40-yea...,False,True,R
76113,RepLeeZeldin,2022-03-01,Great to know that the Vice President has a fi...,False,False,R

In [73]:
from tqdm import tqdm # Import library to have progress bars

def apply_model_to_text(df, text_column, classifier):
    # Initialize tqdm for progress bar
    tqdm.pandas()  # This allows the progress_apply method to work

    # Apply the classifier to the text column and get the result as a DataFrame with a progress bar
    results = df[text_column].progress_apply(lambda x: classifier(x)[0])  # Apply model on each text

    # Create new columns for the label and score
    df['label'] = results.apply(lambda x: x['label'])  # Extract the label
    df['score'] = results.apply(lambda x: x['score'])  # Extract the score

    return df

# Example usage
full_corpus_classified = apply_model_to_text(full_corpus.sample(n=1000), 'text', economy_classifier)

100%|██████████| 1000/1000 [00:25<00:00, 39.40it/s]

In [74]:
full_corpus_classified.value_counts("label")

label
Other      720
Economy    280
Name: count, dtype: int64